### ISSUE TITLE
爬虫已经失效了

### ISSUE THREAD

**Issue by axh2018** [kamust/jxnuJWspider#4]
教务在线对学号进行了加密，地址如下：
https://jwc.jxnu.edu.cn/MyControl/All_Display.aspx?UserControl=All_StudentInfor.ascx&UserType=Student&UserNum=MjAyMDI2ODAzMDAy

**Comment by kamust** [comment]
哇靠，凉凉

**Comment by kamust** [comment]
好像没什么问题呀，照片的地址还是学号，只是基本信息的页面变了usernum，但是这个页面里的信息在查询结果的页面里都有，好像不需要点开去看呀

**Comment by kamust** [comment]
临时给查询结果添加了 'UserNum' 关键字，详见wiki

**Comment by axh2018** [comment]
哎呀，我大意了呀。一看到教务在线给的地址加密了，我啪的一声就过来提了个issue，很快啊。
照片的地址还是正常的。
